#!/usr/bin/env ruby
# -*- ruby -*-
# This script generates the irccodes.h file.  It gets the codes directly from the RFCs.
# Requires HTTParty because I like to party hart™ and can't be bothered with Net::HTTP.
# Install it via 'gem install httparty'
#
# Usage: ruby generate_irccodes_header.rb > ../src/core/irccodes.h

require 'httparty'
require 'erb'

rfcs = %w(1459 2812)  # the RFCs to look for response codes

rfc_base_url = 'http://tools.ietf.org/rfc/rfc%s.txt'  # base url for the RFC in text format
regexp = /^\s+(\d{3})\s+([A-Z]{3}_[A-Z]+)/  # witchcraft

codes = {}

rfcs.each do |rfc|
  doc = HTTParty.get(rfc_base_url % [rfc]).parsed_response

  codes.merge! doc.scan(regexp).map{|x| [x[1], x[0]]}.to_h
end

codes = codes.sort_by{ |_, v| v }.to_h

puts ERB.new(DATA.read).result binding

__END__
// This file was generated by $repo_root/utils/generate_irccodes_header.rb
// <%= Time.now.strftime '%F %T' %>
// -*- C++ -*-
#ifndef IRCCODES_H
#define IRCCODES_H

<% codes.each do |k, v| %>#define <%= k %> <%= v %>
<% end %>
#endif // IRCCODES_H
